### ISSUE TITLE
장바구니 가격

### ISSUE THREAD

**Issue by zZerorok** [ssg-240304-java2/JD-HeadBang#22]
## 어떤 버그인가요?
앨범 가격이 0원으로 출력

## 어떤 상황에서 발생한 버그인가요?
장바구니에 앨범 담기
장바구니 확인할 때 장바구니에 담은 앨범의 가격이 0원으로 출력됨

## 예상 결과
앨범가격이 출력

**Comment by kebin0591** [comment]
![racoon-pedro](https://github.com/ssg-240304-java2/JD-HeadBang/assets/166422645/464f9a20-b536-4051-af10-1e777e103c3e)
